// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi-nomad/sdk/v2/go/nomad/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// URL of the root of the target Nomad agent.
func GetAddress(ctx *pulumi.Context) string {
	return config.Get(ctx, "nomad:address")
}

// A path to a PEM-encoded certificate authority used to verify the remote agent's certificate.
func GetCaFile(ctx *pulumi.Context) string {
	return config.Get(ctx, "nomad:caFile")
}

// PEM-encoded certificate authority used to verify the remote agent's certificate.
func GetCaPem(ctx *pulumi.Context) string {
	return config.Get(ctx, "nomad:caPem")
}

// A path to a PEM-encoded certificate provided to the remote agent; requires use of key_file or key_pem.
func GetCertFile(ctx *pulumi.Context) string {
	return config.Get(ctx, "nomad:certFile")
}

// PEM-encoded certificate provided to the remote agent; requires use of key_file or key_pem.
func GetCertPem(ctx *pulumi.Context) string {
	return config.Get(ctx, "nomad:certPem")
}

// Consul token to validate Consul Connect Service Identity policies specified in the job file.
func GetConsulToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "nomad:consulToken")
}

// The headers to send with each Nomad request.
func GetHeaders(ctx *pulumi.Context) string {
	return config.Get(ctx, "nomad:headers")
}

// HTTP basic auth configuration.
func GetHttpAuth(ctx *pulumi.Context) string {
	return config.Get(ctx, "nomad:httpAuth")
}

// A set of environment variables that are ignored by the provider when configuring the Nomad API client.
func GetIgnoreEnvVars(ctx *pulumi.Context) string {
	return config.Get(ctx, "nomad:ignoreEnvVars")
}

// A path to a PEM-encoded private key, required if cert_file or cert_pem is specified.
func GetKeyFile(ctx *pulumi.Context) string {
	return config.Get(ctx, "nomad:keyFile")
}

// PEM-encoded private key, required if cert_file or cert_pem is specified.
func GetKeyPem(ctx *pulumi.Context) string {
	return config.Get(ctx, "nomad:keyPem")
}

// Region of the target Nomad agent.
func GetRegion(ctx *pulumi.Context) string {
	return config.Get(ctx, "nomad:region")
}

// ACL token secret for API requests.
func GetSecretId(ctx *pulumi.Context) string {
	return config.Get(ctx, "nomad:secretId")
}

// Skip TLS verification on client side.
func GetSkipVerify(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "nomad:skipVerify")
}

// Vault token if policies are specified in the job file.
func GetVaultToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "nomad:vaultToken")
}
