provider: nomad
major-version: 2
setup-script: "testing/setup.sh"
env:
    VAULT_ADDR: "http://127.0.0.1:4646"
makeTemplate: bridged
team: ecosystem
pulumiConvert: 1
registryDocs: true
esc:
    enabled: true
    environment: imports/github-secrets # No repo-specific secrets.
