provider: nomad
major-version: 2
setup-script: "testing/setup.sh"
env:
  VAULT_ADDR: "http://127.0.0.1:4646"
makeTemplate: bridged
plugins:
  - name: terraform
    version: "1.0.16"
    kind: converter

  - name: random
    version: "4.2.0"
team: ecosystem
pulumiConvert: 1
registryDocs: true
