// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nomad.Outputs
{

    [OutputType]
    public sealed class GetJobConstraintResult
    {
        public readonly string Ltarget;
        public readonly string Operand;
        public readonly string Rtarget;

        [OutputConstructor]
        private GetJobConstraintResult(
            string ltarget,

            string operand,

            string rtarget)
        {
            Ltarget = ltarget;
            Operand = operand;
            Rtarget = rtarget;
        }
    }
}
