// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nomad.Outputs
{

    [OutputType]
    public sealed class GetJwksKeyResult
    {
        /// <summary>
        /// `(string)` - JWK field `Alg`
        /// </summary>
        public readonly string Algorithm;
        /// <summary>
        /// `(string)` - JWK field `E`
        /// </summary>
        public readonly string Exponent;
        /// <summary>
        /// `(string)` - JWK field `Kid`
        /// </summary>
        public readonly string KeyId;
        /// <summary>
        /// `(string)` - JWK field `Kty`
        /// </summary>
        public readonly string KeyType;
        /// <summary>
        /// `(string)` - JWK field `Use`
        /// </summary>
        public readonly string KeyUse;
        /// <summary>
        /// `(string)` - JWK field `N`
        /// </summary>
        public readonly string Modulus;

        [OutputConstructor]
        private GetJwksKeyResult(
            string algorithm,

            string exponent,

            string keyId,

            string keyType,

            string keyUse,

            string modulus)
        {
            Algorithm = algorithm;
            Exponent = exponent;
            KeyId = keyId;
            KeyType = keyType;
            KeyUse = keyUse;
            Modulus = modulus;
        }
    }
}
