// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nomad.Outputs
{

    [OutputType]
    public sealed class QuoteSpecificationLimitRegionLimitDevice
    {
        /// <summary>
        /// `(int: 0)` - The number of device instances to limit allocations to.
        /// </summary>
        public readonly int? Count;
        /// <summary>
        /// `(string: &lt;required&gt;)` - The name of the device, e.g.
        /// `"nvidia/gpu"`.
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private QuoteSpecificationLimitRegionLimitDevice(
            int? count,

            string name)
        {
            Count = count;
            Name = name;
        }
    }
}
