// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nomad;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.nomad.ProviderArgs;
import com.pulumi.nomad.Utilities;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * The provider type for the nomad package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 * 
 */
@ResourceType(type="pulumi:providers:nomad")
public class Provider extends com.pulumi.resources.ProviderResource {
    /**
     * URL of the root of the target Nomad agent.
     * 
     */
    @Export(name="address", type=String.class, parameters={})
    private Output<String> address;

    /**
     * @return URL of the root of the target Nomad agent.
     * 
     */
    public Output<String> address() {
        return this.address;
    }
    /**
     * A path to a PEM-encoded certificate authority used to verify the remote agent&#39;s certificate.
     * 
     */
    @Export(name="caFile", type=String.class, parameters={})
    private Output</* @Nullable */ String> caFile;

    /**
     * @return A path to a PEM-encoded certificate authority used to verify the remote agent&#39;s certificate.
     * 
     */
    public Output<Optional<String>> caFile() {
        return Codegen.optional(this.caFile);
    }
    /**
     * PEM-encoded certificate authority used to verify the remote agent&#39;s certificate.
     * 
     */
    @Export(name="caPem", type=String.class, parameters={})
    private Output</* @Nullable */ String> caPem;

    /**
     * @return PEM-encoded certificate authority used to verify the remote agent&#39;s certificate.
     * 
     */
    public Output<Optional<String>> caPem() {
        return Codegen.optional(this.caPem);
    }
    /**
     * A path to a PEM-encoded certificate provided to the remote agent; requires use of key_file or key_pem.
     * 
     */
    @Export(name="certFile", type=String.class, parameters={})
    private Output</* @Nullable */ String> certFile;

    /**
     * @return A path to a PEM-encoded certificate provided to the remote agent; requires use of key_file or key_pem.
     * 
     */
    public Output<Optional<String>> certFile() {
        return Codegen.optional(this.certFile);
    }
    /**
     * PEM-encoded certificate provided to the remote agent; requires use of key_file or key_pem.
     * 
     */
    @Export(name="certPem", type=String.class, parameters={})
    private Output</* @Nullable */ String> certPem;

    /**
     * @return PEM-encoded certificate provided to the remote agent; requires use of key_file or key_pem.
     * 
     */
    public Output<Optional<String>> certPem() {
        return Codegen.optional(this.certPem);
    }
    /**
     * Consul token to validate Consul Connect Service Identity policies specified in the job file.
     * 
     */
    @Export(name="consulToken", type=String.class, parameters={})
    private Output</* @Nullable */ String> consulToken;

    /**
     * @return Consul token to validate Consul Connect Service Identity policies specified in the job file.
     * 
     */
    public Output<Optional<String>> consulToken() {
        return Codegen.optional(this.consulToken);
    }
    /**
     * HTTP basic auth configuration.
     * 
     */
    @Export(name="httpAuth", type=String.class, parameters={})
    private Output</* @Nullable */ String> httpAuth;

    /**
     * @return HTTP basic auth configuration.
     * 
     */
    public Output<Optional<String>> httpAuth() {
        return Codegen.optional(this.httpAuth);
    }
    /**
     * A path to a PEM-encoded private key, required if cert_file or cert_pem is specified.
     * 
     */
    @Export(name="keyFile", type=String.class, parameters={})
    private Output</* @Nullable */ String> keyFile;

    /**
     * @return A path to a PEM-encoded private key, required if cert_file or cert_pem is specified.
     * 
     */
    public Output<Optional<String>> keyFile() {
        return Codegen.optional(this.keyFile);
    }
    /**
     * PEM-encoded private key, required if cert_file or cert_pem is specified.
     * 
     */
    @Export(name="keyPem", type=String.class, parameters={})
    private Output</* @Nullable */ String> keyPem;

    /**
     * @return PEM-encoded private key, required if cert_file or cert_pem is specified.
     * 
     */
    public Output<Optional<String>> keyPem() {
        return Codegen.optional(this.keyPem);
    }
    /**
     * Region of the target Nomad agent.
     * 
     */
    @Export(name="region", type=String.class, parameters={})
    private Output</* @Nullable */ String> region;

    /**
     * @return Region of the target Nomad agent.
     * 
     */
    public Output<Optional<String>> region() {
        return Codegen.optional(this.region);
    }
    /**
     * ACL token secret for API requests.
     * 
     */
    @Export(name="secretId", type=String.class, parameters={})
    private Output</* @Nullable */ String> secretId;

    /**
     * @return ACL token secret for API requests.
     * 
     */
    public Output<Optional<String>> secretId() {
        return Codegen.optional(this.secretId);
    }
    /**
     * Vault token if policies are specified in the job file.
     * 
     */
    @Export(name="vaultToken", type=String.class, parameters={})
    private Output</* @Nullable */ String> vaultToken;

    /**
     * @return Vault token if policies are specified in the job file.
     * 
     */
    public Output<Optional<String>> vaultToken() {
        return Codegen.optional(this.vaultToken);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Provider(String name) {
        this(name, ProviderArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Provider(String name, ProviderArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Provider(String name, ProviderArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("nomad", name, args == null ? ProviderArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

}
