// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nomad;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.nomad.Utilities;
import com.pulumi.nomad.VariableArgs;
import com.pulumi.nomad.inputs.VariableState;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Creates and manages a variable, including it&#39;s contents, within a
 * Nomad cluster.
 * 
 * &gt; **Warning:** this resource will store the sensitive values placed in
 *   `items` in the Terraform&#39;s state file. Take care to
 *   [protect your state file](https://www.terraform.io/docs/state/sensitive-data.html).
 * 
 * ## Example Usage
 * 
 * Creating a variable in the default namespace:
 * 
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.nomad.Variable;
 * import com.pulumi.nomad.VariableArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new Variable("example", VariableArgs.builder()
 *             .path("some/path/of/your/choosing")
 *             .items(Map.of("example_key", "example_value"))
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * 
 * Creating a variable in a custom namespace:
 * 
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.nomad.Namespace;
 * import com.pulumi.nomad.NamespaceArgs;
 * import com.pulumi.nomad.Variable;
 * import com.pulumi.nomad.VariableArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new Namespace("example", NamespaceArgs.builder()
 *             .name("example")
 *             .description("Example namespace.")
 *             .build());
 * 
 *         var exampleVariable = new Variable("exampleVariable", VariableArgs.builder()
 *             .path("some/path/of/your/choosing")
 *             .namespace(example.name())
 *             .items(Map.of("example_key", "example_value"))
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * 
 */
@ResourceType(type="nomad:index/variable:Variable")
public class Variable extends com.pulumi.resources.CustomResource {
    /**
     * `(map[string]string: &lt;required&gt;)` - An arbitrary map of items to create in the variable.
     * 
     */
    @Export(name="items", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output<Map<String,String>> items;

    /**
     * @return `(map[string]string: &lt;required&gt;)` - An arbitrary map of items to create in the variable.
     * 
     */
    public Output<Map<String,String>> items() {
        return this.items;
    }
    /**
     * `(string: &#34;default&#34;)` - The namepsace to create the variable in.
     * 
     */
    @Export(name="namespace", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> namespace;

    /**
     * @return `(string: &#34;default&#34;)` - The namepsace to create the variable in.
     * 
     */
    public Output<Optional<String>> namespace() {
        return Codegen.optional(this.namespace);
    }
    /**
     * `(string: &lt;required&gt;)` - A unique path to create the variable at.
     * 
     */
    @Export(name="path", refs={String.class}, tree="[0]")
    private Output<String> path;

    /**
     * @return `(string: &lt;required&gt;)` - A unique path to create the variable at.
     * 
     */
    public Output<String> path() {
        return this.path;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Variable(java.lang.String name) {
        this(name, VariableArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Variable(java.lang.String name, VariableArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Variable(java.lang.String name, VariableArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("nomad:index/variable:Variable", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Variable(java.lang.String name, Output<java.lang.String> id, @Nullable VariableState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("nomad:index/variable:Variable", name, state, makeResourceOptions(options, id), false);
    }

    private static VariableArgs makeArgs(VariableArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? VariableArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "items"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Variable get(java.lang.String name, Output<java.lang.String> id, @Nullable VariableState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Variable(name, id, state, options);
    }
}
