// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nomad.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetAclPolicyResult {
    /**
     * @return `(string)` - the description of the ACL Policy.
     * 
     */
    private String description;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return `(string)` - the name of the ACL Policy.
     * 
     */
    private String name;
    /**
     * @return `(string)` - the ACL Policy rules in HCL format.
     * 
     */
    private String rules;

    private GetAclPolicyResult() {}
    /**
     * @return `(string)` - the description of the ACL Policy.
     * 
     */
    public String description() {
        return this.description;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return `(string)` - the name of the ACL Policy.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return `(string)` - the ACL Policy rules in HCL format.
     * 
     */
    public String rules() {
        return this.rules;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAclPolicyResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String description;
        private String id;
        private String name;
        private String rules;
        public Builder() {}
        public Builder(GetAclPolicyResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.description = defaults.description;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.rules = defaults.rules;
        }

        @CustomType.Setter
        public Builder description(String description) {
            this.description = Objects.requireNonNull(description);
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }
        @CustomType.Setter
        public Builder rules(String rules) {
            this.rules = Objects.requireNonNull(rules);
            return this;
        }
        public GetAclPolicyResult build() {
            final var o = new GetAclPolicyResult();
            o.description = description;
            o.id = id;
            o.name = name;
            o.rules = rules;
            return o;
        }
    }
}
