// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nomad.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetJobTaskGroupTaskVolumeMount {
    private String destination;
    private Boolean readOnly;
    private String volume;

    private GetJobTaskGroupTaskVolumeMount() {}
    public String destination() {
        return this.destination;
    }
    public Boolean readOnly() {
        return this.readOnly;
    }
    public String volume() {
        return this.volume;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetJobTaskGroupTaskVolumeMount defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String destination;
        private Boolean readOnly;
        private String volume;
        public Builder() {}
        public Builder(GetJobTaskGroupTaskVolumeMount defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.destination = defaults.destination;
    	      this.readOnly = defaults.readOnly;
    	      this.volume = defaults.volume;
        }

        @CustomType.Setter
        public Builder destination(String destination) {
            this.destination = Objects.requireNonNull(destination);
            return this;
        }
        @CustomType.Setter
        public Builder readOnly(Boolean readOnly) {
            this.readOnly = Objects.requireNonNull(readOnly);
            return this;
        }
        @CustomType.Setter
        public Builder volume(String volume) {
            this.volume = Objects.requireNonNull(volume);
            return this;
        }
        public GetJobTaskGroupTaskVolumeMount build() {
            final var _resultValue = new GetJobTaskGroupTaskVolumeMount();
            _resultValue.destination = destination;
            _resultValue.readOnly = readOnly;
            _resultValue.volume = volume;
            return _resultValue;
        }
    }
}
