// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nomad.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.nomad.outputs.GetNodeNodeResourceCpus;
import com.pulumi.nomad.outputs.GetNodeNodeResourceDevice;
import com.pulumi.nomad.outputs.GetNodeNodeResourceDisk;
import com.pulumi.nomad.outputs.GetNodeNodeResourceMemory;
import com.pulumi.nomad.outputs.GetNodeNodeResourceNetwork;
import java.lang.Integer;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetNodeNodeResource {
    /**
     * @return `(list)` - Reserved CPU resources.
     * 
     */
    private List<GetNodeNodeResourceCpus> cpus;
    /**
     * @return `(list)` - Device resources on the node (GPUs, etc.).
     * 
     */
    private List<GetNodeNodeResourceDevice> devices;
    /**
     * @return `(list)` - Reserved disk resources.
     * 
     */
    private List<GetNodeNodeResourceDisk> disks;
    /**
     * @return `(int)` - Maximum dynamic port for this node.
     * 
     */
    private Integer maxDynamicPort;
    /**
     * @return `(list)` - Reserved memory resources.
     * 
     */
    private List<GetNodeNodeResourceMemory> memories;
    /**
     * @return `(int)` - Minimum dynamic port for this node.
     * 
     */
    private Integer minDynamicPort;
    /**
     * @return `(map of string)` - Reserved network resources.
     * 
     */
    private List<GetNodeNodeResourceNetwork> networks;

    private GetNodeNodeResource() {}
    /**
     * @return `(list)` - Reserved CPU resources.
     * 
     */
    public List<GetNodeNodeResourceCpus> cpus() {
        return this.cpus;
    }
    /**
     * @return `(list)` - Device resources on the node (GPUs, etc.).
     * 
     */
    public List<GetNodeNodeResourceDevice> devices() {
        return this.devices;
    }
    /**
     * @return `(list)` - Reserved disk resources.
     * 
     */
    public List<GetNodeNodeResourceDisk> disks() {
        return this.disks;
    }
    /**
     * @return `(int)` - Maximum dynamic port for this node.
     * 
     */
    public Integer maxDynamicPort() {
        return this.maxDynamicPort;
    }
    /**
     * @return `(list)` - Reserved memory resources.
     * 
     */
    public List<GetNodeNodeResourceMemory> memories() {
        return this.memories;
    }
    /**
     * @return `(int)` - Minimum dynamic port for this node.
     * 
     */
    public Integer minDynamicPort() {
        return this.minDynamicPort;
    }
    /**
     * @return `(map of string)` - Reserved network resources.
     * 
     */
    public List<GetNodeNodeResourceNetwork> networks() {
        return this.networks;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNodeNodeResource defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<GetNodeNodeResourceCpus> cpus;
        private List<GetNodeNodeResourceDevice> devices;
        private List<GetNodeNodeResourceDisk> disks;
        private Integer maxDynamicPort;
        private List<GetNodeNodeResourceMemory> memories;
        private Integer minDynamicPort;
        private List<GetNodeNodeResourceNetwork> networks;
        public Builder() {}
        public Builder(GetNodeNodeResource defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.cpus = defaults.cpus;
    	      this.devices = defaults.devices;
    	      this.disks = defaults.disks;
    	      this.maxDynamicPort = defaults.maxDynamicPort;
    	      this.memories = defaults.memories;
    	      this.minDynamicPort = defaults.minDynamicPort;
    	      this.networks = defaults.networks;
        }

        @CustomType.Setter
        public Builder cpus(List<GetNodeNodeResourceCpus> cpus) {
            if (cpus == null) {
              throw new MissingRequiredPropertyException("GetNodeNodeResource", "cpus");
            }
            this.cpus = cpus;
            return this;
        }
        public Builder cpus(GetNodeNodeResourceCpus... cpus) {
            return cpus(List.of(cpus));
        }
        @CustomType.Setter
        public Builder devices(List<GetNodeNodeResourceDevice> devices) {
            if (devices == null) {
              throw new MissingRequiredPropertyException("GetNodeNodeResource", "devices");
            }
            this.devices = devices;
            return this;
        }
        public Builder devices(GetNodeNodeResourceDevice... devices) {
            return devices(List.of(devices));
        }
        @CustomType.Setter
        public Builder disks(List<GetNodeNodeResourceDisk> disks) {
            if (disks == null) {
              throw new MissingRequiredPropertyException("GetNodeNodeResource", "disks");
            }
            this.disks = disks;
            return this;
        }
        public Builder disks(GetNodeNodeResourceDisk... disks) {
            return disks(List.of(disks));
        }
        @CustomType.Setter
        public Builder maxDynamicPort(Integer maxDynamicPort) {
            if (maxDynamicPort == null) {
              throw new MissingRequiredPropertyException("GetNodeNodeResource", "maxDynamicPort");
            }
            this.maxDynamicPort = maxDynamicPort;
            return this;
        }
        @CustomType.Setter
        public Builder memories(List<GetNodeNodeResourceMemory> memories) {
            if (memories == null) {
              throw new MissingRequiredPropertyException("GetNodeNodeResource", "memories");
            }
            this.memories = memories;
            return this;
        }
        public Builder memories(GetNodeNodeResourceMemory... memories) {
            return memories(List.of(memories));
        }
        @CustomType.Setter
        public Builder minDynamicPort(Integer minDynamicPort) {
            if (minDynamicPort == null) {
              throw new MissingRequiredPropertyException("GetNodeNodeResource", "minDynamicPort");
            }
            this.minDynamicPort = minDynamicPort;
            return this;
        }
        @CustomType.Setter
        public Builder networks(List<GetNodeNodeResourceNetwork> networks) {
            if (networks == null) {
              throw new MissingRequiredPropertyException("GetNodeNodeResource", "networks");
            }
            this.networks = networks;
            return this;
        }
        public Builder networks(GetNodeNodeResourceNetwork... networks) {
            return networks(List.of(networks));
        }
        public GetNodeNodeResource build() {
            final var _resultValue = new GetNodeNodeResource();
            _resultValue.cpus = cpus;
            _resultValue.devices = devices;
            _resultValue.disks = disks;
            _resultValue.maxDynamicPort = maxDynamicPort;
            _resultValue.memories = memories;
            _resultValue.minDynamicPort = minDynamicPort;
            _resultValue.networks = networks;
            return _resultValue;
        }
    }
}
