// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nomad.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetNodesNodeNodeResourceCpus {
    /**
     * @return `(int)` - Reserved CPU shares.
     * 
     */
    private Integer cpuShares;
    /**
     * @return `(list of int)` - List of reservable CPU core IDs.
     * 
     */
    private List<Integer> reservableCpuCores;
    /**
     * @return `(int)` - Total number of CPU cores.
     * 
     */
    private Integer totalCpuCores;

    private GetNodesNodeNodeResourceCpus() {}
    /**
     * @return `(int)` - Reserved CPU shares.
     * 
     */
    public Integer cpuShares() {
        return this.cpuShares;
    }
    /**
     * @return `(list of int)` - List of reservable CPU core IDs.
     * 
     */
    public List<Integer> reservableCpuCores() {
        return this.reservableCpuCores;
    }
    /**
     * @return `(int)` - Total number of CPU cores.
     * 
     */
    public Integer totalCpuCores() {
        return this.totalCpuCores;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNodesNodeNodeResourceCpus defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Integer cpuShares;
        private List<Integer> reservableCpuCores;
        private Integer totalCpuCores;
        public Builder() {}
        public Builder(GetNodesNodeNodeResourceCpus defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.cpuShares = defaults.cpuShares;
    	      this.reservableCpuCores = defaults.reservableCpuCores;
    	      this.totalCpuCores = defaults.totalCpuCores;
        }

        @CustomType.Setter
        public Builder cpuShares(Integer cpuShares) {
            if (cpuShares == null) {
              throw new MissingRequiredPropertyException("GetNodesNodeNodeResourceCpus", "cpuShares");
            }
            this.cpuShares = cpuShares;
            return this;
        }
        @CustomType.Setter
        public Builder reservableCpuCores(List<Integer> reservableCpuCores) {
            if (reservableCpuCores == null) {
              throw new MissingRequiredPropertyException("GetNodesNodeNodeResourceCpus", "reservableCpuCores");
            }
            this.reservableCpuCores = reservableCpuCores;
            return this;
        }
        public Builder reservableCpuCores(Integer... reservableCpuCores) {
            return reservableCpuCores(List.of(reservableCpuCores));
        }
        @CustomType.Setter
        public Builder totalCpuCores(Integer totalCpuCores) {
            if (totalCpuCores == null) {
              throw new MissingRequiredPropertyException("GetNodesNodeNodeResourceCpus", "totalCpuCores");
            }
            this.totalCpuCores = totalCpuCores;
            return this;
        }
        public GetNodesNodeNodeResourceCpus build() {
            final var _resultValue = new GetNodesNodeNodeResourceCpus();
            _resultValue.cpuShares = cpuShares;
            _resultValue.reservableCpuCores = reservableCpuCores;
            _resultValue.totalCpuCores = totalCpuCores;
            return _resultValue;
        }
    }
}
