// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nomad.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.nomad.outputs.GetNodesNode;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetNodesResult {
    private @Nullable String filter;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return `(list of nodes)` - A list of nodes matching the search criteria.
     * 
     */
    private List<GetNodesNode> nodes;
    private @Nullable Boolean os;
    private @Nullable String prefix;
    private @Nullable Boolean resources;

    private GetNodesResult() {}
    public Optional<String> filter() {
        return Optional.ofNullable(this.filter);
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return `(list of nodes)` - A list of nodes matching the search criteria.
     * 
     */
    public List<GetNodesNode> nodes() {
        return this.nodes;
    }
    public Optional<Boolean> os() {
        return Optional.ofNullable(this.os);
    }
    public Optional<String> prefix() {
        return Optional.ofNullable(this.prefix);
    }
    public Optional<Boolean> resources() {
        return Optional.ofNullable(this.resources);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNodesResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String filter;
        private String id;
        private List<GetNodesNode> nodes;
        private @Nullable Boolean os;
        private @Nullable String prefix;
        private @Nullable Boolean resources;
        public Builder() {}
        public Builder(GetNodesResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.filter = defaults.filter;
    	      this.id = defaults.id;
    	      this.nodes = defaults.nodes;
    	      this.os = defaults.os;
    	      this.prefix = defaults.prefix;
    	      this.resources = defaults.resources;
        }

        @CustomType.Setter
        public Builder filter(@Nullable String filter) {

            this.filter = filter;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetNodesResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder nodes(List<GetNodesNode> nodes) {
            if (nodes == null) {
              throw new MissingRequiredPropertyException("GetNodesResult", "nodes");
            }
            this.nodes = nodes;
            return this;
        }
        public Builder nodes(GetNodesNode... nodes) {
            return nodes(List.of(nodes));
        }
        @CustomType.Setter
        public Builder os(@Nullable Boolean os) {

            this.os = os;
            return this;
        }
        @CustomType.Setter
        public Builder prefix(@Nullable String prefix) {

            this.prefix = prefix;
            return this;
        }
        @CustomType.Setter
        public Builder resources(@Nullable Boolean resources) {

            this.resources = resources;
            return this;
        }
        public GetNodesResult build() {
            final var _resultValue = new GetNodesResult();
            _resultValue.filter = filter;
            _resultValue.id = id;
            _resultValue.nodes = nodes;
            _resultValue.os = os;
            _resultValue.prefix = prefix;
            _resultValue.resources = resources;
            return _resultValue;
        }
    }
}
