// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nomad.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class NamespaceVaultConfig {
    /**
     * @return `([]string: &lt;optional&gt;)` - The list of Vault clusters allowed to be used in this namespace. Cannot be used with `denied`.
     * 
     */
    private @Nullable List<String> alloweds;
    /**
     * @return `(string: &lt;optional&gt;)` - The Vault cluster to use when none is specified in the job.
     * 
     */
    private @Nullable String default_;
    /**
     * @return `([]string: &lt;optional&gt;)` - The list of Vault clusters not allowed to be used in this namespace. Cannot be used with `allowed`.
     * 
     */
    private @Nullable List<String> denieds;

    private NamespaceVaultConfig() {}
    /**
     * @return `([]string: &lt;optional&gt;)` - The list of Vault clusters allowed to be used in this namespace. Cannot be used with `denied`.
     * 
     */
    public List<String> alloweds() {
        return this.alloweds == null ? List.of() : this.alloweds;
    }
    /**
     * @return `(string: &lt;optional&gt;)` - The Vault cluster to use when none is specified in the job.
     * 
     */
    public Optional<String> default_() {
        return Optional.ofNullable(this.default_);
    }
    /**
     * @return `([]string: &lt;optional&gt;)` - The list of Vault clusters not allowed to be used in this namespace. Cannot be used with `allowed`.
     * 
     */
    public List<String> denieds() {
        return this.denieds == null ? List.of() : this.denieds;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NamespaceVaultConfig defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<String> alloweds;
        private @Nullable String default_;
        private @Nullable List<String> denieds;
        public Builder() {}
        public Builder(NamespaceVaultConfig defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.alloweds = defaults.alloweds;
    	      this.default_ = defaults.default_;
    	      this.denieds = defaults.denieds;
        }

        @CustomType.Setter
        public Builder alloweds(@Nullable List<String> alloweds) {

            this.alloweds = alloweds;
            return this;
        }
        public Builder alloweds(String... alloweds) {
            return alloweds(List.of(alloweds));
        }
        @CustomType.Setter("default")
        public Builder default_(@Nullable String default_) {

            this.default_ = default_;
            return this;
        }
        @CustomType.Setter
        public Builder denieds(@Nullable List<String> denieds) {

            this.denieds = denieds;
            return this;
        }
        public Builder denieds(String... denieds) {
            return denieds(List.of(denieds));
        }
        public NamespaceVaultConfig build() {
            final var _resultValue = new NamespaceVaultConfig();
            _resultValue.alloweds = alloweds;
            _resultValue.default_ = default_;
            _resultValue.denieds = denieds;
            return _resultValue;
        }
    }
}
