// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nomad.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.nomad.inputs.CsiVolumeTopologyRequestRequiredTopologyArgs;
import java.util.List;
import java.util.Objects;


public final class CsiVolumeTopologyRequestRequiredArgs extends com.pulumi.resources.ResourceArgs {

    public static final CsiVolumeTopologyRequestRequiredArgs Empty = new CsiVolumeTopologyRequestRequiredArgs();

    /**
     * Defines the location for the volume.
     * 
     */
    @Import(name="topologies", required=true)
    private Output<List<CsiVolumeTopologyRequestRequiredTopologyArgs>> topologies;

    /**
     * @return Defines the location for the volume.
     * 
     */
    public Output<List<CsiVolumeTopologyRequestRequiredTopologyArgs>> topologies() {
        return this.topologies;
    }

    private CsiVolumeTopologyRequestRequiredArgs() {}

    private CsiVolumeTopologyRequestRequiredArgs(CsiVolumeTopologyRequestRequiredArgs $) {
        this.topologies = $.topologies;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CsiVolumeTopologyRequestRequiredArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CsiVolumeTopologyRequestRequiredArgs $;

        public Builder() {
            $ = new CsiVolumeTopologyRequestRequiredArgs();
        }

        public Builder(CsiVolumeTopologyRequestRequiredArgs defaults) {
            $ = new CsiVolumeTopologyRequestRequiredArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param topologies Defines the location for the volume.
         * 
         * @return builder
         * 
         */
        public Builder topologies(Output<List<CsiVolumeTopologyRequestRequiredTopologyArgs>> topologies) {
            $.topologies = topologies;
            return this;
        }

        /**
         * @param topologies Defines the location for the volume.
         * 
         * @return builder
         * 
         */
        public Builder topologies(List<CsiVolumeTopologyRequestRequiredTopologyArgs> topologies) {
            return topologies(Output.of(topologies));
        }

        /**
         * @param topologies Defines the location for the volume.
         * 
         * @return builder
         * 
         */
        public Builder topologies(CsiVolumeTopologyRequestRequiredTopologyArgs... topologies) {
            return topologies(List.of(topologies));
        }

        public CsiVolumeTopologyRequestRequiredArgs build() {
            if ($.topologies == null) {
                throw new MissingRequiredPropertyException("CsiVolumeTopologyRequestRequiredArgs", "topologies");
            }
            return $;
        }
    }

}
