// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nomad.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.nomad.inputs.CsiVolumeCapabilityArgs;
import com.pulumi.nomad.inputs.CsiVolumeMountOptionsArgs;
import com.pulumi.nomad.inputs.CsiVolumeTopologyArgs;
import com.pulumi.nomad.inputs.CsiVolumeTopologyRequestArgs;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class CsiVolumeState extends com.pulumi.resources.ResourceArgs {

    public static final CsiVolumeState Empty = new CsiVolumeState();

    /**
     * `(``Capability``: &lt;required&gt;)` - Options for validating the capability of a volume.
     * 
     */
    @Import(name="capabilities")
    private @Nullable Output<List<CsiVolumeCapabilityArgs>> capabilities;

    /**
     * @return `(``Capability``: &lt;required&gt;)` - Options for validating the capability of a volume.
     * 
     */
    public Optional<Output<List<CsiVolumeCapabilityArgs>>> capabilities() {
        return Optional.ofNullable(this.capabilities);
    }

    /**
     * `(string: &lt;optional&gt;)` - Option to signal a maximum volume size. This may not be supported by all storage providers.
     * 
     */
    @Import(name="capacityMax")
    private @Nullable Output<String> capacityMax;

    /**
     * @return `(string: &lt;optional&gt;)` - Option to signal a maximum volume size. This may not be supported by all storage providers.
     * 
     */
    public Optional<Output<String>> capacityMax() {
        return Optional.ofNullable(this.capacityMax);
    }

    /**
     * `(string: &lt;optional&gt;)` - Option to signal a minimum volume size. This may not be supported by all storage providers.
     * 
     */
    @Import(name="capacityMin")
    private @Nullable Output<String> capacityMin;

    /**
     * @return `(string: &lt;optional&gt;)` - Option to signal a minimum volume size. This may not be supported by all storage providers.
     * 
     */
    public Optional<Output<String>> capacityMin() {
        return Optional.ofNullable(this.capacityMin);
    }

    /**
     * `(string: &lt;optional&gt;)` - The external ID of an existing volume to restore. If ommited, the volume will be created from scratch. Conflicts with `snapshot_id`.
     * 
     */
    @Import(name="cloneId")
    private @Nullable Output<String> cloneId;

    /**
     * @return `(string: &lt;optional&gt;)` - The external ID of an existing volume to restore. If ommited, the volume will be created from scratch. Conflicts with `snapshot_id`.
     * 
     */
    public Optional<Output<String>> cloneId() {
        return Optional.ofNullable(this.cloneId);
    }

    /**
     * `(boolean)`
     * 
     */
    @Import(name="controllerRequired")
    private @Nullable Output<Boolean> controllerRequired;

    /**
     * @return `(boolean)`
     * 
     */
    public Optional<Output<Boolean>> controllerRequired() {
        return Optional.ofNullable(this.controllerRequired);
    }

    /**
     * `(integer)`
     * 
     */
    @Import(name="controllersExpected")
    private @Nullable Output<Integer> controllersExpected;

    /**
     * @return `(integer)`
     * 
     */
    public Optional<Output<Integer>> controllersExpected() {
        return Optional.ofNullable(this.controllersExpected);
    }

    /**
     * `(integer)`
     * 
     */
    @Import(name="controllersHealthy")
    private @Nullable Output<Integer> controllersHealthy;

    /**
     * @return `(integer)`
     * 
     */
    public Optional<Output<Integer>> controllersHealthy() {
        return Optional.ofNullable(this.controllersHealthy);
    }

    /**
     * `(block: optional)` Options for mounting `block-device` volumes without a pre-formatted file system.
     * 
     */
    @Import(name="mountOptions")
    private @Nullable Output<CsiVolumeMountOptionsArgs> mountOptions;

    /**
     * @return `(block: optional)` Options for mounting `block-device` volumes without a pre-formatted file system.
     * 
     */
    public Optional<Output<CsiVolumeMountOptionsArgs>> mountOptions() {
        return Optional.ofNullable(this.mountOptions);
    }

    /**
     * `(string: &lt;required&gt;)` - The display name for the volume.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return `(string: &lt;required&gt;)` - The display name for the volume.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * `(string: &#34;default&#34;)` - The namespace in which to register the volume.
     * 
     */
    @Import(name="namespace")
    private @Nullable Output<String> namespace;

    /**
     * @return `(string: &#34;default&#34;)` - The namespace in which to register the volume.
     * 
     */
    public Optional<Output<String>> namespace() {
        return Optional.ofNullable(this.namespace);
    }

    /**
     * `(integer)`
     * 
     */
    @Import(name="nodesExpected")
    private @Nullable Output<Integer> nodesExpected;

    /**
     * @return `(integer)`
     * 
     */
    public Optional<Output<Integer>> nodesExpected() {
        return Optional.ofNullable(this.nodesExpected);
    }

    /**
     * `(integer)`
     * 
     */
    @Import(name="nodesHealthy")
    private @Nullable Output<Integer> nodesHealthy;

    /**
     * @return `(integer)`
     * 
     */
    public Optional<Output<Integer>> nodesHealthy() {
        return Optional.ofNullable(this.nodesHealthy);
    }

    /**
     * `(map[string]string: optional)` An optional key-value map of strings passed directly to the CSI plugin to configure the volume.
     * 
     */
    @Import(name="parameters")
    private @Nullable Output<Map<String,String>> parameters;

    /**
     * @return `(map[string]string: optional)` An optional key-value map of strings passed directly to the CSI plugin to configure the volume.
     * 
     */
    public Optional<Output<Map<String,String>>> parameters() {
        return Optional.ofNullable(this.parameters);
    }

    /**
     * `(string: &lt;required&gt;)` - The ID of the Nomad plugin for registering this volume.
     * 
     */
    @Import(name="pluginId")
    private @Nullable Output<String> pluginId;

    /**
     * @return `(string: &lt;required&gt;)` - The ID of the Nomad plugin for registering this volume.
     * 
     */
    public Optional<Output<String>> pluginId() {
        return Optional.ofNullable(this.pluginId);
    }

    /**
     * `(string)`
     * 
     */
    @Import(name="pluginProvider")
    private @Nullable Output<String> pluginProvider;

    /**
     * @return `(string)`
     * 
     */
    public Optional<Output<String>> pluginProvider() {
        return Optional.ofNullable(this.pluginProvider);
    }

    /**
     * `(string)`
     * 
     */
    @Import(name="pluginProviderVersion")
    private @Nullable Output<String> pluginProviderVersion;

    /**
     * @return `(string)`
     * 
     */
    public Optional<Output<String>> pluginProviderVersion() {
        return Optional.ofNullable(this.pluginProviderVersion);
    }

    /**
     * `(boolean)`
     * 
     */
    @Import(name="schedulable")
    private @Nullable Output<Boolean> schedulable;

    /**
     * @return `(boolean)`
     * 
     */
    public Optional<Output<Boolean>> schedulable() {
        return Optional.ofNullable(this.schedulable);
    }

    /**
     * `(map[string]string: optional)` An optional key-value map of strings used as credentials for publishing and unpublishing volumes.
     * 
     */
    @Import(name="secrets")
    private @Nullable Output<Map<String,String>> secrets;

    /**
     * @return `(map[string]string: optional)` An optional key-value map of strings used as credentials for publishing and unpublishing volumes.
     * 
     */
    public Optional<Output<Map<String,String>>> secrets() {
        return Optional.ofNullable(this.secrets);
    }

    /**
     * `(string: &lt;optional&gt;)` - The external ID of a snapshot to restore. If ommited, the volume will be created from scratch. Conflicts with `clone_id`.
     * 
     */
    @Import(name="snapshotId")
    private @Nullable Output<String> snapshotId;

    /**
     * @return `(string: &lt;optional&gt;)` - The external ID of a snapshot to restore. If ommited, the volume will be created from scratch. Conflicts with `clone_id`.
     * 
     */
    public Optional<Output<String>> snapshotId() {
        return Optional.ofNullable(this.snapshotId);
    }

    /**
     * `(List of topologies)`
     * 
     */
    @Import(name="topologies")
    private @Nullable Output<List<CsiVolumeTopologyArgs>> topologies;

    /**
     * @return `(List of topologies)`
     * 
     */
    public Optional<Output<List<CsiVolumeTopologyArgs>>> topologies() {
        return Optional.ofNullable(this.topologies);
    }

    /**
     * `(``TopologyRequest``: &lt;optional&gt;)` - Specify locations (region, zone, rack, etc.) where the provisioned volume is accessible from.
     * 
     */
    @Import(name="topologyRequest")
    private @Nullable Output<CsiVolumeTopologyRequestArgs> topologyRequest;

    /**
     * @return `(``TopologyRequest``: &lt;optional&gt;)` - Specify locations (region, zone, rack, etc.) where the provisioned volume is accessible from.
     * 
     */
    public Optional<Output<CsiVolumeTopologyRequestArgs>> topologyRequest() {
        return Optional.ofNullable(this.topologyRequest);
    }

    /**
     * `(string: &lt;required&gt;)` - The unique ID of the volume.
     * 
     */
    @Import(name="volumeId")
    private @Nullable Output<String> volumeId;

    /**
     * @return `(string: &lt;required&gt;)` - The unique ID of the volume.
     * 
     */
    public Optional<Output<String>> volumeId() {
        return Optional.ofNullable(this.volumeId);
    }

    private CsiVolumeState() {}

    private CsiVolumeState(CsiVolumeState $) {
        this.capabilities = $.capabilities;
        this.capacityMax = $.capacityMax;
        this.capacityMin = $.capacityMin;
        this.cloneId = $.cloneId;
        this.controllerRequired = $.controllerRequired;
        this.controllersExpected = $.controllersExpected;
        this.controllersHealthy = $.controllersHealthy;
        this.mountOptions = $.mountOptions;
        this.name = $.name;
        this.namespace = $.namespace;
        this.nodesExpected = $.nodesExpected;
        this.nodesHealthy = $.nodesHealthy;
        this.parameters = $.parameters;
        this.pluginId = $.pluginId;
        this.pluginProvider = $.pluginProvider;
        this.pluginProviderVersion = $.pluginProviderVersion;
        this.schedulable = $.schedulable;
        this.secrets = $.secrets;
        this.snapshotId = $.snapshotId;
        this.topologies = $.topologies;
        this.topologyRequest = $.topologyRequest;
        this.volumeId = $.volumeId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CsiVolumeState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CsiVolumeState $;

        public Builder() {
            $ = new CsiVolumeState();
        }

        public Builder(CsiVolumeState defaults) {
            $ = new CsiVolumeState(Objects.requireNonNull(defaults));
        }

        /**
         * @param capabilities `(``Capability``: &lt;required&gt;)` - Options for validating the capability of a volume.
         * 
         * @return builder
         * 
         */
        public Builder capabilities(@Nullable Output<List<CsiVolumeCapabilityArgs>> capabilities) {
            $.capabilities = capabilities;
            return this;
        }

        /**
         * @param capabilities `(``Capability``: &lt;required&gt;)` - Options for validating the capability of a volume.
         * 
         * @return builder
         * 
         */
        public Builder capabilities(List<CsiVolumeCapabilityArgs> capabilities) {
            return capabilities(Output.of(capabilities));
        }

        /**
         * @param capabilities `(``Capability``: &lt;required&gt;)` - Options for validating the capability of a volume.
         * 
         * @return builder
         * 
         */
        public Builder capabilities(CsiVolumeCapabilityArgs... capabilities) {
            return capabilities(List.of(capabilities));
        }

        /**
         * @param capacityMax `(string: &lt;optional&gt;)` - Option to signal a maximum volume size. This may not be supported by all storage providers.
         * 
         * @return builder
         * 
         */
        public Builder capacityMax(@Nullable Output<String> capacityMax) {
            $.capacityMax = capacityMax;
            return this;
        }

        /**
         * @param capacityMax `(string: &lt;optional&gt;)` - Option to signal a maximum volume size. This may not be supported by all storage providers.
         * 
         * @return builder
         * 
         */
        public Builder capacityMax(String capacityMax) {
            return capacityMax(Output.of(capacityMax));
        }

        /**
         * @param capacityMin `(string: &lt;optional&gt;)` - Option to signal a minimum volume size. This may not be supported by all storage providers.
         * 
         * @return builder
         * 
         */
        public Builder capacityMin(@Nullable Output<String> capacityMin) {
            $.capacityMin = capacityMin;
            return this;
        }

        /**
         * @param capacityMin `(string: &lt;optional&gt;)` - Option to signal a minimum volume size. This may not be supported by all storage providers.
         * 
         * @return builder
         * 
         */
        public Builder capacityMin(String capacityMin) {
            return capacityMin(Output.of(capacityMin));
        }

        /**
         * @param cloneId `(string: &lt;optional&gt;)` - The external ID of an existing volume to restore. If ommited, the volume will be created from scratch. Conflicts with `snapshot_id`.
         * 
         * @return builder
         * 
         */
        public Builder cloneId(@Nullable Output<String> cloneId) {
            $.cloneId = cloneId;
            return this;
        }

        /**
         * @param cloneId `(string: &lt;optional&gt;)` - The external ID of an existing volume to restore. If ommited, the volume will be created from scratch. Conflicts with `snapshot_id`.
         * 
         * @return builder
         * 
         */
        public Builder cloneId(String cloneId) {
            return cloneId(Output.of(cloneId));
        }

        /**
         * @param controllerRequired `(boolean)`
         * 
         * @return builder
         * 
         */
        public Builder controllerRequired(@Nullable Output<Boolean> controllerRequired) {
            $.controllerRequired = controllerRequired;
            return this;
        }

        /**
         * @param controllerRequired `(boolean)`
         * 
         * @return builder
         * 
         */
        public Builder controllerRequired(Boolean controllerRequired) {
            return controllerRequired(Output.of(controllerRequired));
        }

        /**
         * @param controllersExpected `(integer)`
         * 
         * @return builder
         * 
         */
        public Builder controllersExpected(@Nullable Output<Integer> controllersExpected) {
            $.controllersExpected = controllersExpected;
            return this;
        }

        /**
         * @param controllersExpected `(integer)`
         * 
         * @return builder
         * 
         */
        public Builder controllersExpected(Integer controllersExpected) {
            return controllersExpected(Output.of(controllersExpected));
        }

        /**
         * @param controllersHealthy `(integer)`
         * 
         * @return builder
         * 
         */
        public Builder controllersHealthy(@Nullable Output<Integer> controllersHealthy) {
            $.controllersHealthy = controllersHealthy;
            return this;
        }

        /**
         * @param controllersHealthy `(integer)`
         * 
         * @return builder
         * 
         */
        public Builder controllersHealthy(Integer controllersHealthy) {
            return controllersHealthy(Output.of(controllersHealthy));
        }

        /**
         * @param mountOptions `(block: optional)` Options for mounting `block-device` volumes without a pre-formatted file system.
         * 
         * @return builder
         * 
         */
        public Builder mountOptions(@Nullable Output<CsiVolumeMountOptionsArgs> mountOptions) {
            $.mountOptions = mountOptions;
            return this;
        }

        /**
         * @param mountOptions `(block: optional)` Options for mounting `block-device` volumes without a pre-formatted file system.
         * 
         * @return builder
         * 
         */
        public Builder mountOptions(CsiVolumeMountOptionsArgs mountOptions) {
            return mountOptions(Output.of(mountOptions));
        }

        /**
         * @param name `(string: &lt;required&gt;)` - The display name for the volume.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name `(string: &lt;required&gt;)` - The display name for the volume.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param namespace `(string: &#34;default&#34;)` - The namespace in which to register the volume.
         * 
         * @return builder
         * 
         */
        public Builder namespace(@Nullable Output<String> namespace) {
            $.namespace = namespace;
            return this;
        }

        /**
         * @param namespace `(string: &#34;default&#34;)` - The namespace in which to register the volume.
         * 
         * @return builder
         * 
         */
        public Builder namespace(String namespace) {
            return namespace(Output.of(namespace));
        }

        /**
         * @param nodesExpected `(integer)`
         * 
         * @return builder
         * 
         */
        public Builder nodesExpected(@Nullable Output<Integer> nodesExpected) {
            $.nodesExpected = nodesExpected;
            return this;
        }

        /**
         * @param nodesExpected `(integer)`
         * 
         * @return builder
         * 
         */
        public Builder nodesExpected(Integer nodesExpected) {
            return nodesExpected(Output.of(nodesExpected));
        }

        /**
         * @param nodesHealthy `(integer)`
         * 
         * @return builder
         * 
         */
        public Builder nodesHealthy(@Nullable Output<Integer> nodesHealthy) {
            $.nodesHealthy = nodesHealthy;
            return this;
        }

        /**
         * @param nodesHealthy `(integer)`
         * 
         * @return builder
         * 
         */
        public Builder nodesHealthy(Integer nodesHealthy) {
            return nodesHealthy(Output.of(nodesHealthy));
        }

        /**
         * @param parameters `(map[string]string: optional)` An optional key-value map of strings passed directly to the CSI plugin to configure the volume.
         * 
         * @return builder
         * 
         */
        public Builder parameters(@Nullable Output<Map<String,String>> parameters) {
            $.parameters = parameters;
            return this;
        }

        /**
         * @param parameters `(map[string]string: optional)` An optional key-value map of strings passed directly to the CSI plugin to configure the volume.
         * 
         * @return builder
         * 
         */
        public Builder parameters(Map<String,String> parameters) {
            return parameters(Output.of(parameters));
        }

        /**
         * @param pluginId `(string: &lt;required&gt;)` - The ID of the Nomad plugin for registering this volume.
         * 
         * @return builder
         * 
         */
        public Builder pluginId(@Nullable Output<String> pluginId) {
            $.pluginId = pluginId;
            return this;
        }

        /**
         * @param pluginId `(string: &lt;required&gt;)` - The ID of the Nomad plugin for registering this volume.
         * 
         * @return builder
         * 
         */
        public Builder pluginId(String pluginId) {
            return pluginId(Output.of(pluginId));
        }

        /**
         * @param pluginProvider `(string)`
         * 
         * @return builder
         * 
         */
        public Builder pluginProvider(@Nullable Output<String> pluginProvider) {
            $.pluginProvider = pluginProvider;
            return this;
        }

        /**
         * @param pluginProvider `(string)`
         * 
         * @return builder
         * 
         */
        public Builder pluginProvider(String pluginProvider) {
            return pluginProvider(Output.of(pluginProvider));
        }

        /**
         * @param pluginProviderVersion `(string)`
         * 
         * @return builder
         * 
         */
        public Builder pluginProviderVersion(@Nullable Output<String> pluginProviderVersion) {
            $.pluginProviderVersion = pluginProviderVersion;
            return this;
        }

        /**
         * @param pluginProviderVersion `(string)`
         * 
         * @return builder
         * 
         */
        public Builder pluginProviderVersion(String pluginProviderVersion) {
            return pluginProviderVersion(Output.of(pluginProviderVersion));
        }

        /**
         * @param schedulable `(boolean)`
         * 
         * @return builder
         * 
         */
        public Builder schedulable(@Nullable Output<Boolean> schedulable) {
            $.schedulable = schedulable;
            return this;
        }

        /**
         * @param schedulable `(boolean)`
         * 
         * @return builder
         * 
         */
        public Builder schedulable(Boolean schedulable) {
            return schedulable(Output.of(schedulable));
        }

        /**
         * @param secrets `(map[string]string: optional)` An optional key-value map of strings used as credentials for publishing and unpublishing volumes.
         * 
         * @return builder
         * 
         */
        public Builder secrets(@Nullable Output<Map<String,String>> secrets) {
            $.secrets = secrets;
            return this;
        }

        /**
         * @param secrets `(map[string]string: optional)` An optional key-value map of strings used as credentials for publishing and unpublishing volumes.
         * 
         * @return builder
         * 
         */
        public Builder secrets(Map<String,String> secrets) {
            return secrets(Output.of(secrets));
        }

        /**
         * @param snapshotId `(string: &lt;optional&gt;)` - The external ID of a snapshot to restore. If ommited, the volume will be created from scratch. Conflicts with `clone_id`.
         * 
         * @return builder
         * 
         */
        public Builder snapshotId(@Nullable Output<String> snapshotId) {
            $.snapshotId = snapshotId;
            return this;
        }

        /**
         * @param snapshotId `(string: &lt;optional&gt;)` - The external ID of a snapshot to restore. If ommited, the volume will be created from scratch. Conflicts with `clone_id`.
         * 
         * @return builder
         * 
         */
        public Builder snapshotId(String snapshotId) {
            return snapshotId(Output.of(snapshotId));
        }

        /**
         * @param topologies `(List of topologies)`
         * 
         * @return builder
         * 
         */
        public Builder topologies(@Nullable Output<List<CsiVolumeTopologyArgs>> topologies) {
            $.topologies = topologies;
            return this;
        }

        /**
         * @param topologies `(List of topologies)`
         * 
         * @return builder
         * 
         */
        public Builder topologies(List<CsiVolumeTopologyArgs> topologies) {
            return topologies(Output.of(topologies));
        }

        /**
         * @param topologies `(List of topologies)`
         * 
         * @return builder
         * 
         */
        public Builder topologies(CsiVolumeTopologyArgs... topologies) {
            return topologies(List.of(topologies));
        }

        /**
         * @param topologyRequest `(``TopologyRequest``: &lt;optional&gt;)` - Specify locations (region, zone, rack, etc.) where the provisioned volume is accessible from.
         * 
         * @return builder
         * 
         */
        public Builder topologyRequest(@Nullable Output<CsiVolumeTopologyRequestArgs> topologyRequest) {
            $.topologyRequest = topologyRequest;
            return this;
        }

        /**
         * @param topologyRequest `(``TopologyRequest``: &lt;optional&gt;)` - Specify locations (region, zone, rack, etc.) where the provisioned volume is accessible from.
         * 
         * @return builder
         * 
         */
        public Builder topologyRequest(CsiVolumeTopologyRequestArgs topologyRequest) {
            return topologyRequest(Output.of(topologyRequest));
        }

        /**
         * @param volumeId `(string: &lt;required&gt;)` - The unique ID of the volume.
         * 
         * @return builder
         * 
         */
        public Builder volumeId(@Nullable Output<String> volumeId) {
            $.volumeId = volumeId;
            return this;
        }

        /**
         * @param volumeId `(string: &lt;required&gt;)` - The unique ID of the volume.
         * 
         * @return builder
         * 
         */
        public Builder volumeId(String volumeId) {
            return volumeId(Output.of(volumeId));
        }

        public CsiVolumeState build() {
            return $;
        }
    }

}
