// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nomad.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.nomad.inputs.ExternalVolumeTopologyRequestPreferredArgs;
import com.pulumi.nomad.inputs.ExternalVolumeTopologyRequestRequiredArgs;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ExternalVolumeTopologyRequestArgs extends com.pulumi.resources.ResourceArgs {

    public static final ExternalVolumeTopologyRequestArgs Empty = new ExternalVolumeTopologyRequestArgs();

    @Import(name="preferred")
    private @Nullable Output<ExternalVolumeTopologyRequestPreferredArgs> preferred;

    public Optional<Output<ExternalVolumeTopologyRequestPreferredArgs>> preferred() {
        return Optional.ofNullable(this.preferred);
    }

    @Import(name="required")
    private @Nullable Output<ExternalVolumeTopologyRequestRequiredArgs> required;

    public Optional<Output<ExternalVolumeTopologyRequestRequiredArgs>> required() {
        return Optional.ofNullable(this.required);
    }

    private ExternalVolumeTopologyRequestArgs() {}

    private ExternalVolumeTopologyRequestArgs(ExternalVolumeTopologyRequestArgs $) {
        this.preferred = $.preferred;
        this.required = $.required;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ExternalVolumeTopologyRequestArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ExternalVolumeTopologyRequestArgs $;

        public Builder() {
            $ = new ExternalVolumeTopologyRequestArgs();
        }

        public Builder(ExternalVolumeTopologyRequestArgs defaults) {
            $ = new ExternalVolumeTopologyRequestArgs(Objects.requireNonNull(defaults));
        }

        public Builder preferred(@Nullable Output<ExternalVolumeTopologyRequestPreferredArgs> preferred) {
            $.preferred = preferred;
            return this;
        }

        public Builder preferred(ExternalVolumeTopologyRequestPreferredArgs preferred) {
            return preferred(Output.of(preferred));
        }

        public Builder required(@Nullable Output<ExternalVolumeTopologyRequestRequiredArgs> required) {
            $.required = required;
            return this;
        }

        public Builder required(ExternalVolumeTopologyRequestRequiredArgs required) {
            return required(Output.of(required));
        }

        public ExternalVolumeTopologyRequestArgs build() {
            return $;
        }
    }

}
