// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nomad.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetNodesPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetNodesPlainArgs Empty = new GetNodesPlainArgs();

    /**
     * `(string: &lt;optional&gt;)` - Specifies the [expression][nomadApiFilter]
     * used to filter the results.
     * 
     */
    @Import(name="filter")
    private @Nullable String filter;

    /**
     * @return `(string: &lt;optional&gt;)` - Specifies the [expression][nomadApiFilter]
     * used to filter the results.
     * 
     */
    public Optional<String> filter() {
        return Optional.ofNullable(this.filter);
    }

    /**
     * `(bool: false)` - If true, include special attributes such as operating
     * system name in the response. When false, the `attributes` map will not contain
     * OS-related attributes.
     * 
     */
    @Import(name="os")
    private @Nullable Boolean os;

    /**
     * @return `(bool: false)` - If true, include special attributes such as operating
     * system name in the response. When false, the `attributes` map will not contain
     * OS-related attributes.
     * 
     */
    public Optional<Boolean> os() {
        return Optional.ofNullable(this.os);
    }

    /**
     * `(string: &lt;optional&gt;)` - Specifies a string to filter nodes based on
     * an ID prefix. Must have an even number of hexadecimal characters (0-9a-f).
     * 
     */
    @Import(name="prefix")
    private @Nullable String prefix;

    /**
     * @return `(string: &lt;optional&gt;)` - Specifies a string to filter nodes based on
     * an ID prefix. Must have an even number of hexadecimal characters (0-9a-f).
     * 
     */
    public Optional<String> prefix() {
        return Optional.ofNullable(this.prefix);
    }

    /**
     * `(bool: false)` - If true, include `nodeResources` and
     * `reservedResources` in the response.
     * 
     */
    @Import(name="resources")
    private @Nullable Boolean resources;

    /**
     * @return `(bool: false)` - If true, include `nodeResources` and
     * `reservedResources` in the response.
     * 
     */
    public Optional<Boolean> resources() {
        return Optional.ofNullable(this.resources);
    }

    private GetNodesPlainArgs() {}

    private GetNodesPlainArgs(GetNodesPlainArgs $) {
        this.filter = $.filter;
        this.os = $.os;
        this.prefix = $.prefix;
        this.resources = $.resources;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetNodesPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetNodesPlainArgs $;

        public Builder() {
            $ = new GetNodesPlainArgs();
        }

        public Builder(GetNodesPlainArgs defaults) {
            $ = new GetNodesPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param filter `(string: &lt;optional&gt;)` - Specifies the [expression][nomadApiFilter]
         * used to filter the results.
         * 
         * @return builder
         * 
         */
        public Builder filter(@Nullable String filter) {
            $.filter = filter;
            return this;
        }

        /**
         * @param os `(bool: false)` - If true, include special attributes such as operating
         * system name in the response. When false, the `attributes` map will not contain
         * OS-related attributes.
         * 
         * @return builder
         * 
         */
        public Builder os(@Nullable Boolean os) {
            $.os = os;
            return this;
        }

        /**
         * @param prefix `(string: &lt;optional&gt;)` - Specifies a string to filter nodes based on
         * an ID prefix. Must have an even number of hexadecimal characters (0-9a-f).
         * 
         * @return builder
         * 
         */
        public Builder prefix(@Nullable String prefix) {
            $.prefix = prefix;
            return this;
        }

        /**
         * @param resources `(bool: false)` - If true, include `nodeResources` and
         * `reservedResources` in the response.
         * 
         * @return builder
         * 
         */
        public Builder resources(@Nullable Boolean resources) {
            $.resources = resources;
            return this;
        }

        public GetNodesPlainArgs build() {
            return $;
        }
    }

}
