// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nomad.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetPluginArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetPluginArgs Empty = new GetPluginArgs();

    @Import(name="pluginId", required=true)
    private Output<String> pluginId;

    public Output<String> pluginId() {
        return this.pluginId;
    }

    @Import(name="waitForHealthy")
    private @Nullable Output<Boolean> waitForHealthy;

    public Optional<Output<Boolean>> waitForHealthy() {
        return Optional.ofNullable(this.waitForHealthy);
    }

    @Import(name="waitForRegistration")
    private @Nullable Output<Boolean> waitForRegistration;

    public Optional<Output<Boolean>> waitForRegistration() {
        return Optional.ofNullable(this.waitForRegistration);
    }

    private GetPluginArgs() {}

    private GetPluginArgs(GetPluginArgs $) {
        this.pluginId = $.pluginId;
        this.waitForHealthy = $.waitForHealthy;
        this.waitForRegistration = $.waitForRegistration;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetPluginArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetPluginArgs $;

        public Builder() {
            $ = new GetPluginArgs();
        }

        public Builder(GetPluginArgs defaults) {
            $ = new GetPluginArgs(Objects.requireNonNull(defaults));
        }

        public Builder pluginId(Output<String> pluginId) {
            $.pluginId = pluginId;
            return this;
        }

        public Builder pluginId(String pluginId) {
            return pluginId(Output.of(pluginId));
        }

        public Builder waitForHealthy(@Nullable Output<Boolean> waitForHealthy) {
            $.waitForHealthy = waitForHealthy;
            return this;
        }

        public Builder waitForHealthy(Boolean waitForHealthy) {
            return waitForHealthy(Output.of(waitForHealthy));
        }

        public Builder waitForRegistration(@Nullable Output<Boolean> waitForRegistration) {
            $.waitForRegistration = waitForRegistration;
            return this;
        }

        public Builder waitForRegistration(Boolean waitForRegistration) {
            return waitForRegistration(Output.of(waitForRegistration));
        }

        public GetPluginArgs build() {
            $.pluginId = Objects.requireNonNull($.pluginId, "expected parameter 'pluginId' to be non-null");
            return $;
        }
    }

}
