// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nomad.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class JobUpdateStrategyArgs extends com.pulumi.resources.ResourceArgs {

    public static final JobUpdateStrategyArgs Empty = new JobUpdateStrategyArgs();

    /**
     * `(boolean)` - Whether the job should automatically revert to the last stable job on deployment failure.
     * 
     */
    @Import(name="autoRevert")
    private @Nullable Output<Boolean> autoRevert;

    /**
     * @return `(boolean)` - Whether the job should automatically revert to the last stable job on deployment failure.
     * 
     */
    public Optional<Output<Boolean>> autoRevert() {
        return Optional.ofNullable(this.autoRevert);
    }

    /**
     * `(integer)` - Number of canary allocations created before destructive updates continue.
     * 
     */
    @Import(name="canary")
    private @Nullable Output<Integer> canary;

    /**
     * @return `(integer)` - Number of canary allocations created before destructive updates continue.
     * 
     */
    public Optional<Output<Integer>> canary() {
        return Optional.ofNullable(this.canary);
    }

    /**
     * `(string)` - Mechanism used to determine allocation health: `checks`, `taskStates`, or `manual`.
     * 
     */
    @Import(name="healthCheck")
    private @Nullable Output<String> healthCheck;

    /**
     * @return `(string)` - Mechanism used to determine allocation health: `checks`, `taskStates`, or `manual`.
     * 
     */
    public Optional<Output<String>> healthCheck() {
        return Optional.ofNullable(this.healthCheck);
    }

    /**
     * `(string)` - Deadline by which the allocation must become healthy before it is marked unhealthy.
     * 
     */
    @Import(name="healthyDeadline")
    private @Nullable Output<String> healthyDeadline;

    /**
     * @return `(string)` - Deadline by which the allocation must become healthy before it is marked unhealthy.
     * 
     */
    public Optional<Output<String>> healthyDeadline() {
        return Optional.ofNullable(this.healthyDeadline);
    }

    /**
     * `(integer)` - Number of allocations within a task group that can be destructively updated at the same time. Setting `0` forces updates instead of deployments.
     * 
     */
    @Import(name="maxParallel")
    private @Nullable Output<Integer> maxParallel;

    /**
     * @return `(integer)` - Number of allocations within a task group that can be destructively updated at the same time. Setting `0` forces updates instead of deployments.
     * 
     */
    public Optional<Output<Integer>> maxParallel() {
        return Optional.ofNullable(this.maxParallel);
    }

    /**
     * `(string)` - Minimum time the allocation must be in the healthy state before further updates can proceed.
     * 
     */
    @Import(name="minHealthyTime")
    private @Nullable Output<String> minHealthyTime;

    /**
     * @return `(string)` - Minimum time the allocation must be in the healthy state before further updates can proceed.
     * 
     */
    public Optional<Output<String>> minHealthyTime() {
        return Optional.ofNullable(this.minHealthyTime);
    }

    /**
     * `(string)` - Delay between each set of `maxParallel` updates when updating system jobs.
     * 
     */
    @Import(name="stagger")
    private @Nullable Output<String> stagger;

    /**
     * @return `(string)` - Delay between each set of `maxParallel` updates when updating system jobs.
     * 
     */
    public Optional<Output<String>> stagger() {
        return Optional.ofNullable(this.stagger);
    }

    private JobUpdateStrategyArgs() {}

    private JobUpdateStrategyArgs(JobUpdateStrategyArgs $) {
        this.autoRevert = $.autoRevert;
        this.canary = $.canary;
        this.healthCheck = $.healthCheck;
        this.healthyDeadline = $.healthyDeadline;
        this.maxParallel = $.maxParallel;
        this.minHealthyTime = $.minHealthyTime;
        this.stagger = $.stagger;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(JobUpdateStrategyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private JobUpdateStrategyArgs $;

        public Builder() {
            $ = new JobUpdateStrategyArgs();
        }

        public Builder(JobUpdateStrategyArgs defaults) {
            $ = new JobUpdateStrategyArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param autoRevert `(boolean)` - Whether the job should automatically revert to the last stable job on deployment failure.
         * 
         * @return builder
         * 
         */
        public Builder autoRevert(@Nullable Output<Boolean> autoRevert) {
            $.autoRevert = autoRevert;
            return this;
        }

        /**
         * @param autoRevert `(boolean)` - Whether the job should automatically revert to the last stable job on deployment failure.
         * 
         * @return builder
         * 
         */
        public Builder autoRevert(Boolean autoRevert) {
            return autoRevert(Output.of(autoRevert));
        }

        /**
         * @param canary `(integer)` - Number of canary allocations created before destructive updates continue.
         * 
         * @return builder
         * 
         */
        public Builder canary(@Nullable Output<Integer> canary) {
            $.canary = canary;
            return this;
        }

        /**
         * @param canary `(integer)` - Number of canary allocations created before destructive updates continue.
         * 
         * @return builder
         * 
         */
        public Builder canary(Integer canary) {
            return canary(Output.of(canary));
        }

        /**
         * @param healthCheck `(string)` - Mechanism used to determine allocation health: `checks`, `taskStates`, or `manual`.
         * 
         * @return builder
         * 
         */
        public Builder healthCheck(@Nullable Output<String> healthCheck) {
            $.healthCheck = healthCheck;
            return this;
        }

        /**
         * @param healthCheck `(string)` - Mechanism used to determine allocation health: `checks`, `taskStates`, or `manual`.
         * 
         * @return builder
         * 
         */
        public Builder healthCheck(String healthCheck) {
            return healthCheck(Output.of(healthCheck));
        }

        /**
         * @param healthyDeadline `(string)` - Deadline by which the allocation must become healthy before it is marked unhealthy.
         * 
         * @return builder
         * 
         */
        public Builder healthyDeadline(@Nullable Output<String> healthyDeadline) {
            $.healthyDeadline = healthyDeadline;
            return this;
        }

        /**
         * @param healthyDeadline `(string)` - Deadline by which the allocation must become healthy before it is marked unhealthy.
         * 
         * @return builder
         * 
         */
        public Builder healthyDeadline(String healthyDeadline) {
            return healthyDeadline(Output.of(healthyDeadline));
        }

        /**
         * @param maxParallel `(integer)` - Number of allocations within a task group that can be destructively updated at the same time. Setting `0` forces updates instead of deployments.
         * 
         * @return builder
         * 
         */
        public Builder maxParallel(@Nullable Output<Integer> maxParallel) {
            $.maxParallel = maxParallel;
            return this;
        }

        /**
         * @param maxParallel `(integer)` - Number of allocations within a task group that can be destructively updated at the same time. Setting `0` forces updates instead of deployments.
         * 
         * @return builder
         * 
         */
        public Builder maxParallel(Integer maxParallel) {
            return maxParallel(Output.of(maxParallel));
        }

        /**
         * @param minHealthyTime `(string)` - Minimum time the allocation must be in the healthy state before further updates can proceed.
         * 
         * @return builder
         * 
         */
        public Builder minHealthyTime(@Nullable Output<String> minHealthyTime) {
            $.minHealthyTime = minHealthyTime;
            return this;
        }

        /**
         * @param minHealthyTime `(string)` - Minimum time the allocation must be in the healthy state before further updates can proceed.
         * 
         * @return builder
         * 
         */
        public Builder minHealthyTime(String minHealthyTime) {
            return minHealthyTime(Output.of(minHealthyTime));
        }

        /**
         * @param stagger `(string)` - Delay between each set of `maxParallel` updates when updating system jobs.
         * 
         * @return builder
         * 
         */
        public Builder stagger(@Nullable Output<String> stagger) {
            $.stagger = stagger;
            return this;
        }

        /**
         * @param stagger `(string)` - Delay between each set of `maxParallel` updates when updating system jobs.
         * 
         * @return builder
         * 
         */
        public Builder stagger(String stagger) {
            return stagger(Output.of(stagger));
        }

        public JobUpdateStrategyArgs build() {
            return $;
        }
    }

}
