// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nomad.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.nomad.inputs.VolumeTopologyRequestRequiredArgs;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class VolumeTopologyRequestArgs extends com.pulumi.resources.ResourceArgs {

    public static final VolumeTopologyRequestArgs Empty = new VolumeTopologyRequestArgs();

    @Import(name="required")
    private @Nullable Output<VolumeTopologyRequestRequiredArgs> required;

    public Optional<Output<VolumeTopologyRequestRequiredArgs>> required() {
        return Optional.ofNullable(this.required);
    }

    private VolumeTopologyRequestArgs() {}

    private VolumeTopologyRequestArgs(VolumeTopologyRequestArgs $) {
        this.required = $.required;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(VolumeTopologyRequestArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private VolumeTopologyRequestArgs $;

        public Builder() {
            $ = new VolumeTopologyRequestArgs();
        }

        public Builder(VolumeTopologyRequestArgs defaults) {
            $ = new VolumeTopologyRequestArgs(Objects.requireNonNull(defaults));
        }

        public Builder required(@Nullable Output<VolumeTopologyRequestRequiredArgs> required) {
            $.required = required;
            return this;
        }

        public Builder required(VolumeTopologyRequestRequiredArgs required) {
            return required(Output.of(required));
        }

        public VolumeTopologyRequestArgs build() {
            return $;
        }
    }

}
