// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package nomad

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Retrieve a Scaling Policy.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-nomad/sdk/go/nomad"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := nomad.GetScalingPolicy(ctx, &nomad.GetScalingPolicyArgs{
// 			Id: "ad19848d-1921-179c-affa-244a3543be88",
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func GetScalingPolicy(ctx *pulumi.Context, args *GetScalingPolicyArgs, opts ...pulumi.InvokeOption) (*GetScalingPolicyResult, error) {
	var rv GetScalingPolicyResult
	err := ctx.Invoke("nomad:index/getScalingPolicy:getScalingPolicy", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getScalingPolicy.
type GetScalingPolicyArgs struct {
	// `(string: <required>)` - The  ID of the scaling policy.
	Id string `pulumi:"id"`
}

// A collection of values returned by getScalingPolicy.
type GetScalingPolicyResult struct {
	Enabled bool                   `pulumi:"enabled"`
	Id      string                 `pulumi:"id"`
	Max     int                    `pulumi:"max"`
	Min     int                    `pulumi:"min"`
	Policy  string                 `pulumi:"policy"`
	Target  map[string]interface{} `pulumi:"target"`
	Type    string                 `pulumi:"type"`
}
