// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package nomad

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Retrieve a list of Scaling Policies.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-nomad/sdk/go/nomad"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		opt0 := "webapp"
// 		opt1 := "horizontal"
// 		_, err := nomad.GetScalingPolicies(ctx, &nomad.GetScalingPoliciesArgs{
// 			JobId: &opt0,
// 			Type:  &opt1,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func GetScalingPolicies(ctx *pulumi.Context, args *GetScalingPoliciesArgs, opts ...pulumi.InvokeOption) (*GetScalingPoliciesResult, error) {
	var rv GetScalingPoliciesResult
	err := ctx.Invoke("nomad:index/getScalingPolicies:getScalingPolicies", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getScalingPolicies.
type GetScalingPoliciesArgs struct {
	// `(string)` - An optional string to filter scaling policies based on the target job. If not provided, policies for all jobs are returned.
	JobId *string `pulumi:"jobId"`
	// `(string)` - An optional string to filter scaling policies based on policy type. If not provided, policies of all types are returned.
	Type *string `pulumi:"type"`
}

// A collection of values returned by getScalingPolicies.
type GetScalingPoliciesResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id       string                     `pulumi:"id"`
	JobId    *string                    `pulumi:"jobId"`
	Policies []GetScalingPoliciesPolicy `pulumi:"policies"`
	Type     *string                    `pulumi:"type"`
}
