// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nomad.Inputs
{

    public sealed class DynamicHostVolumeConstraintArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// `(string)` - The [node attribute][] to check for the constraint.
        /// </summary>
        [Input("attribute", required: true)]
        public Input<string> Attribute { get; set; } = null!;

        /// <summary>
        /// `(string)`- The operator to use in the comparison.
        /// </summary>
        [Input("operator")]
        public Input<string>? Operator { get; set; }

        /// <summary>
        /// `(string)` - The value of the attribute to compare against.
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public DynamicHostVolumeConstraintArgs()
        {
        }
        public static new DynamicHostVolumeConstraintArgs Empty => new DynamicHostVolumeConstraintArgs();
    }
}
