// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nomad.Inputs
{

    public sealed class JobTaskGroupVolumeArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// `(string)` - Volume name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// `(boolean)` - Whether the volume is read-only.
        /// </summary>
        [Input("readOnly")]
        public Input<bool>? ReadOnly { get; set; }

        /// <summary>
        /// `(string)` - Volume source.
        /// </summary>
        [Input("source")]
        public Input<string>? Source { get; set; }

        /// <summary>
        /// `(string)` - Volume type.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public JobTaskGroupVolumeArgs()
        {
        }
        public static new JobTaskGroupVolumeArgs Empty => new JobTaskGroupVolumeArgs();
    }
}
