// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nomad.Inputs
{

    public sealed class ProviderAuthJwtArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the auth method to use for login.
        /// </summary>
        [Input("authMethod", required: true)]
        public Input<string> AuthMethod { get; set; } = null!;

        /// <summary>
        /// The externally issued authentication token to be exchanged for a Nomad ACL Token.
        /// </summary>
        [Input("loginToken", required: true)]
        public Input<string> LoginToken { get; set; } = null!;

        public ProviderAuthJwtArgs()
        {
        }
        public static new ProviderAuthJwtArgs Empty => new ProviderAuthJwtArgs();
    }
}
