// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nomad.Inputs
{

    public sealed class QuoteSpecificationLimitRegionLimitNodePoolArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// `(int: 0)` - The number of CPU cores to limit allocations to. A value
        /// of zero is treated as unlimited, and a negative value is treated as fully
        /// disallowed.
        /// </summary>
        [Input("cores")]
        public Input<int>? Cores { get; set; }

        /// <summary>
        /// `(int: 0)` - The amount of CPU to limit allocations to. A value of zero
        /// is treated as unlimited, and a negative value is treated as fully disallowed.
        /// </summary>
        [Input("cpu")]
        public Input<int>? Cpu { get; set; }

        [Input("devices")]
        private InputList<Inputs.QuoteSpecificationLimitRegionLimitNodePoolDeviceArgs>? _devices;
        public InputList<Inputs.QuoteSpecificationLimitRegionLimitNodePoolDeviceArgs> Devices
        {
            get => _devices ?? (_devices = new InputList<Inputs.QuoteSpecificationLimitRegionLimitNodePoolDeviceArgs>());
            set => _devices = value;
        }

        /// <summary>
        /// `(int: 0)` - The maximum amount of memory (in megabytes) to
        /// limit allocations to. A value of zero is treated as unlimited, and a negative
        /// value is treated as fully disallowed.
        /// - `Devices` `(block: optional)` - A list of device quotas to
        /// enforce for the node pool. Can be repeated.
        /// - `Storage` `(block: optional)` - Storage resource quota
        /// configuration for the node pool. May only be specified once.
        /// </summary>
        [Input("memoryMaxMb")]
        public Input<int>? MemoryMaxMb { get; set; }

        /// <summary>
        /// `(int: 0)` - The amount of memory (in megabytes) to limit
        /// allocations to. A value of zero is treated as unlimited, and a negative value
        /// is treated as fully disallowed.
        /// </summary>
        [Input("memoryMb")]
        public Input<int>? MemoryMb { get; set; }

        /// <summary>
        /// `(string: &lt;required&gt;)` - The node pool name to apply limits to.
        /// </summary>
        [Input("nodePool", required: true)]
        public Input<string> NodePool { get; set; } = null!;

        [Input("storage")]
        public Input<Inputs.QuoteSpecificationLimitRegionLimitNodePoolStorageArgs>? Storage { get; set; }

        public QuoteSpecificationLimitRegionLimitNodePoolArgs()
        {
        }
        public static new QuoteSpecificationLimitRegionLimitNodePoolArgs Empty => new QuoteSpecificationLimitRegionLimitNodePoolArgs();
    }
}
