// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * Retrieve a list of ACL Policies.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as nomad from "@pulumi/nomad";
 *
 * const example = pulumi.output(nomad.getAclPolicies({
 *     prefix: "prod",
 * }));
 * ```
 */
export function getAclPolicies(args?: GetAclPoliciesArgs, opts?: pulumi.InvokeOptions): Promise<GetAclPoliciesResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("nomad:index/getAclPolicies:getAclPolicies", {
        "prefix": args.prefix,
    }, opts);
}

/**
 * A collection of arguments for invoking getAclPolicies.
 */
export interface GetAclPoliciesArgs {
    prefix?: string;
}

/**
 * A collection of values returned by getAclPolicies.
 */
export interface GetAclPoliciesResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly policies: outputs.GetAclPoliciesPolicy[];
    readonly prefix?: string;
}
