// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * The provider type for the nomad package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'nomad';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * URL of the root of the target Nomad agent.
     */
    declare public readonly address: pulumi.Output<string | undefined>;
    /**
     * A path to a PEM-encoded certificate authority used to verify the remote agent's certificate.
     */
    declare public readonly caFile: pulumi.Output<string | undefined>;
    /**
     * PEM-encoded certificate authority used to verify the remote agent's certificate.
     */
    declare public readonly caPem: pulumi.Output<string | undefined>;
    /**
     * A path to a PEM-encoded certificate provided to the remote agent; requires use of keyFile or key_pem.
     */
    declare public readonly certFile: pulumi.Output<string | undefined>;
    /**
     * PEM-encoded certificate provided to the remote agent; requires use of keyFile or key_pem.
     */
    declare public readonly certPem: pulumi.Output<string | undefined>;
    /**
     * HTTP basic auth configuration.
     */
    declare public readonly httpAuth: pulumi.Output<string | undefined>;
    /**
     * A path to a PEM-encoded private key, required if certFile or certPem is specified.
     */
    declare public readonly keyFile: pulumi.Output<string | undefined>;
    /**
     * PEM-encoded private key, required if certFile or certPem is specified.
     */
    declare public readonly keyPem: pulumi.Output<string | undefined>;
    /**
     * Region of the target Nomad agent.
     */
    declare public readonly region: pulumi.Output<string | undefined>;
    /**
     * ACL token secret for API requests.
     */
    declare public readonly secretId: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["address"] = args?.address;
            resourceInputs["authJwt"] = pulumi.output(args?.authJwt).apply(JSON.stringify);
            resourceInputs["caFile"] = args?.caFile;
            resourceInputs["caPem"] = args?.caPem;
            resourceInputs["certFile"] = args?.certFile;
            resourceInputs["certPem"] = args?.certPem;
            resourceInputs["headers"] = pulumi.output(args?.headers ? pulumi.secret(args.headers) : undefined).apply(JSON.stringify);
            resourceInputs["httpAuth"] = args?.httpAuth;
            resourceInputs["ignoreEnvVars"] = pulumi.output(args?.ignoreEnvVars).apply(JSON.stringify);
            resourceInputs["keyFile"] = args?.keyFile;
            resourceInputs["keyPem"] = args?.keyPem;
            resourceInputs["region"] = args?.region;
            resourceInputs["secretId"] = args?.secretId;
            resourceInputs["skipVerify"] = pulumi.output(args?.skipVerify).apply(JSON.stringify);
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }

    /**
     * This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
     */
    terraformConfig(): pulumi.Output<Provider.TerraformConfigResult> {
        return pulumi.runtime.call("pulumi:providers:nomad/terraformConfig", {
            "__self__": this,
        }, this);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * URL of the root of the target Nomad agent.
     */
    address?: pulumi.Input<string>;
    /**
     * Authenticates to Nomad using a JWT authentication method.
     */
    authJwt?: pulumi.Input<inputs.ProviderAuthJwt>;
    /**
     * A path to a PEM-encoded certificate authority used to verify the remote agent's certificate.
     */
    caFile?: pulumi.Input<string>;
    /**
     * PEM-encoded certificate authority used to verify the remote agent's certificate.
     */
    caPem?: pulumi.Input<string>;
    /**
     * A path to a PEM-encoded certificate provided to the remote agent; requires use of keyFile or key_pem.
     */
    certFile?: pulumi.Input<string>;
    /**
     * PEM-encoded certificate provided to the remote agent; requires use of keyFile or key_pem.
     */
    certPem?: pulumi.Input<string>;
    /**
     * The headers to send with each Nomad request.
     */
    headers?: pulumi.Input<pulumi.Input<inputs.ProviderHeader>[]>;
    /**
     * HTTP basic auth configuration.
     */
    httpAuth?: pulumi.Input<string>;
    /**
     * A set of environment variables that are ignored by the provider when configuring the Nomad API client.
     */
    ignoreEnvVars?: pulumi.Input<{[key: string]: pulumi.Input<boolean>}>;
    /**
     * A path to a PEM-encoded private key, required if certFile or certPem is specified.
     */
    keyFile?: pulumi.Input<string>;
    /**
     * PEM-encoded private key, required if certFile or certPem is specified.
     */
    keyPem?: pulumi.Input<string>;
    /**
     * Region of the target Nomad agent.
     */
    region?: pulumi.Input<string>;
    /**
     * ACL token secret for API requests.
     */
    secretId?: pulumi.Input<string>;
    /**
     * Skip TLS verification on client side.
     */
    skipVerify?: pulumi.Input<boolean>;
}

export namespace Provider {
    /**
     * The results of the Provider.terraformConfig method.
     */
    export interface TerraformConfigResult {
        readonly result: {[key: string]: any};
    }

}
